### ISSUE TITLE
Component class should extend React component to avoid warnings

### ISSUE THREAD

**Issue by sjdemartini** [yelled3/react-native-google-static-map#1]
Currently seeing warnings due to the component being a standard ES6 class that does not extend `React.component`: 
![image](https://cloud.githubusercontent.com/assets/1647130/11798815/4a0fe342-a283-11e5-99e0-7c43e067fc8c.png)

**Comment by yelled3** [comment]
@sjdemartini fixed.
https://github.com/yelled3/react-native-google-static-map/commit/e43f843484067ca02bc60f29c89c8b62e0e65529
