### ISSUE TITLE
The prop 'apiKey' is marked as required in 'GoogleStaticMap'

### ISSUE THREAD

**Issue by bvv218** [yelled3/react-native-google-static-map#14]
I am using 'key' prop and it works great but I always have this warning: ```Failed prop type: The prop 'apiKey' is marked as required in 'GoogleStaticMap'```

P.S. I tried using 'apiKey' instead but map doesn't show up.

**Comment by yelled3** [comment]
```
apiKey: PropTypes.string.isRequired,
```

https://github.com/yelled3/react-native-google-static-map/blob/master/GoogleStaticMap.js#L115

**Comment by bvv218** [comment]
@yelled3 The problem is that when I use 'apiKey' prop, map doesn't work at all.
