### ISSUE TITLE
Map doesn't show up

### ISSUE THREAD

**Issue by Twinbird24** [yelled3/react-native-google-static-map#18]
When I'm not using the `apiKey` property, the map shows up and I get a warning `Warning: Failed prop type: The prop 'apiKey' is marked as required in 'GoogleStaticMap', but its value is 'undefined'`. However, when I add a valid API key, the warning disappears but the map is no longer visible. When I inspect the page, I can see content there for "GoogleStaticMap" (i.e. it takes up space) but it's just all white, no content.

**Comment by janajri** [comment]
@Twinbird24 I encountered a similar issue -- forking and fixing the apiKey ref fixed it for me. 

https://github.com/Phocustech/react-native-google-static-map/commit/944b99b65951951d33f6bd18502507e860aef109

Feel free to use my fork -- otherwise maybe we can get @yelled3 to make this update.

**Comment by Twinbird24** [comment]
Awesome, thanks @janajri!

**Comment by yelled3** [comment]
@Twinbird24  @janajri Thanks for the help.
fixed on `0.1.12`
https://github.com/yelled3/react-native-google-static-map/commit/8caf3addd31ba2f0ac2ade4e95f1d2ba66c36631
